const fs = require('fs')
const path = require('path')
const express = require('express')
// const favicon = require('serve-favicon')
// const bodyParser = require('body-parser')
// const cookieParser = require('cookie-parser')
const db = require('./db.js')
// const resolve = file => path.resolve(__dirname, file)
// const api = require('./api')
const app = express()
